### ISSUE TITLE
telegraf is limiting their access...

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Unified-Multilanguage-Reader#155]
we should probably remove it from the list... or pay for a subscription on the server?

<img width="970" alt="screenshot 2017-05-26 20 55 09" src="https://cloud.githubusercontent.com/assets/464519/26508612/b164bd88-4255-11e7-8d39-38a67f52cb70.png">

**Comment by Lukeslux** [comment]
Some articles work, sometimes. It will also never actually stop giving us premium articles, it's like a bad parent: it keeps warning us but never follows trough.

**Comment by mircealungu** [comment]
it works
