### ISSUE TITLE
Internet Explorer does not show article links

### ISSUE THREAD

**Issue by Lukeslux** [zeeguu-ecosystem/Unified-Multilanguage-Reader#202]

**Comment by DanChirtoaca** [comment]
The error on IE is bound to its support for javascript

![image](https://user-images.githubusercontent.com/17150553/26921109-5579c348-4c3b-11e7-97b2-d9a6eb76076e.png)

"Object does not support this action" is related to:

![image](https://user-images.githubusercontent.com/17150553/26920887-aec47066-4c3a-11e7-81d2-187b28e9f9ef.png)

Not sure if changing the architecture to adapt for IE is really worth the effort.
