### ISSUE TITLE
META - Review issues

### ISSUE THREAD

**Issue by Lukeslux** [zeeguu-ecosystem/Unified-Multilanguage-Reader#279]
Kind of a meta issue: I think this issue page needs to be cleaned and reviewed. Maybe a short rl meeting resolve this quickly. @mircealungu ?

**Comment by mircealungu** [comment]
Thanks for observing this @Lukeslux ! Indeed, it would be good to do a cleanup! 
if rl = real life then we'll have to do it sometime after January 5th.

**Comment by Lukeslux** [comment]
Yes, that's what I meant ;)
Will January 9th work?

**Comment by mircealungu** [comment]
9th at 4pm would be perfect!

**Comment by Lukeslux** [comment]
Unfortunately, I will have a lecture at that time.
How about the 10th, any time should do for me.
