### ISSUE TITLE
we must discuss search interaction

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Unified-Multilanguage-Reader#331]
when a search is displayed, we need to have a message saying that this is the result of the search. then, when that message is closed, the usual subscriptions should be displayed. or something like this.

**Comment by Feikoritsema** [comment]
I do agree. There are a few ways to do this: 

- A message above the articles (which I think will look kind of ugly)
- A snackbar message like the things shown when it couldn't connect or find any articles, make it indefinite and when someone clicks the x, we reload normal articles.

Any preference or would you like me to look for others?

**Comment by mircealungu** [comment]
You seem to prefer the second. Let's do that :)

**Comment by mircealungu** [comment]
Hi Feiko! 

Sorry to hear this is more painful than it should. 

Maybe it's sufficient to just add a very subtle message
at the top of the page which would say "Results for searching for Blablabla (x)" with a little x button that would hide the element and show the usual subscriptions?

**Comment by mircealungu** [comment]
maybe the easiest is to simply render the following message at the top of the page: 
"Results for searching for Blablabla. Refresh page for your normal subscriptions".
Not the coolest, but easy to do. Although just as easy to add the "x" button which does the page refresh.

**Comment by Feikoritsema** [comment]
The actual text and button isn't the real problem. 

The main thing I am facing is that the UI is really clean and some random text somewhere would kind of mess that up, I will try to position it well though :)

**Comment by Feikoritsema** [comment]
This should now be resolved in #321 👍

**Comment by mircealungu** [comment]
And it looks quite nice :)
